package com.nxchien.chpmusic.ui.tabs.feature;

import android.content.Context;
import android.content.res.ColorStateList;
import android.graphics.Bitmap;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.RippleDrawable;
import android.os.AsyncTask;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.AnimationUtils;
import android.widget.ImageView;
import android.widget.TextView;


import com.nxchien.chpmusic.util.AutoGeneratedPlaylistBitmap;
import com.nxchien.chpmusic.ui.widget.BounceInterpolator;
import com.nxchien.chpmusic.util.Tool;
import com.nxchien.chpmusic.R;
import com.nxchien.chpmusic.loader.LastAddedLoader;
import com.nxchien.chpmusic.loader.PlaylistSongLoader;
import com.nxchien.chpmusic.loader.SongLoader;
import com.nxchien.chpmusic.loader.TopTracksLoader;
import com.nxchien.chpmusic.model.Playlist;
import com.nxchien.chpmusic.model.Song;
import com.nxchien.chpmusic.util.Utils;
import com.makeramen.roundedimageview.RoundedDrawable;

import java.util.ArrayList;
import java.util.List;

public class FeaturePlaylistAdapter extends RecyclerView.Adapter<FeaturePlaylistAdapter.ItemHolder> {
    private static final String TAG = "PlaylistAdapter";
    public ArrayList<Playlist> mPlaylistData = new ArrayList<>();

    public FeaturePlaylistAdapter setListener(PlaylistClickListener listener) {
        mListener = listener;
        return this;
    }

    public PlaylistClickListener mListener;
    private Context mContext;
    private boolean showAuto;
    private int songCountInt;
    private long firstAlbumID=-1;
    public interface PlaylistClickListener {
        void onClickPlaylist(Playlist playlist, Bitmap bitmap);
    }

    public FeaturePlaylistAdapter(Context mContext, boolean showAuto) {
        this.mContext = mContext;
        this.showAuto = showAuto;
    }

    public void setData(List<Playlist> data) {
        mPlaylistData.clear();
        if(data!=null) {
            mPlaylistData.addAll(data);
            notifyDataSetChanged();

        }
    }

    @Override
    public ItemHolder onCreateViewHolder( ViewGroup viewGroup, int i) {
        View v = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.item_feature_playlist, viewGroup,false);
        return new ItemHolder(v);
    }
    @Override
    public void onBindViewHolder( final ItemHolder itemHolder, int i) {
        // Lấy item Playlist thứ i
        final Playlist playlist = mPlaylistData.get(i);

        new PlaylistBitmapLoader(this,playlist,itemHolder).execute();

         itemHolder.art.setTag(firstAlbumID);
         itemHolder.title.setText(playlist.name);
        if(Utils.isLollipop()) itemHolder.art.setTransitionName("transition_album_art"+i);
    }


    private Bitmap getImagePlaylist(int position, Playlist playlist) {
        List<Song> l =getPlaylistWithListId(position,playlist.id);
        return AutoGeneratedPlaylistBitmap.getBitmap(mContext,l,true,false);

    }

    @Override
    public int getItemCount() {
        return  mPlaylistData.size();
    }


    public List<Song> getPlaylistWithListId(int position, long id) {
        if(mContext!=null) {
            firstAlbumID = -1;
            if(showAuto) {
                switch (position) {
                    case 0: return  LastAddedLoader.getLastAddedSongs(mContext);
                    case 1:
                        return SongLoader.getSongsForCursor(TopTracksLoader.getCursor());
                    case 2:
                        return SongLoader.getSongsForCursor(TopTracksLoader.getCursor());
                    default:
                        return PlaylistSongLoader.getSongsInPlaylist(mContext, id);
                }
            } else PlaylistSongLoader.getSongsInPlaylist(mContext, id);
        }
        return null;
    }

    public class ItemHolder extends RecyclerView.ViewHolder implements View.OnClickListener,View.OnTouchListener{
        protected TextView title;
        protected ImageView art;
        View view_over;
        protected View root;
        int currentColor=0;
        ItemHolder(View view) {
            super(view);
            root = view;
            this.title = view.findViewById(R.id.playlist_title);
            this.art = view.findViewById(R.id.playlist_image);
            view_over = view.findViewById(R.id.playlist_over);
            view_over.setOnClickListener(this);
            view_over.setOnTouchListener(this);
        }
        @Override
        public void onClick(View v) {
            final android.view.animation.Animation myAnim = AnimationUtils.loadAnimation(mContext, R.anim.bounce_slow);
            BounceInterpolator interpolator = new BounceInterpolator(0.1, 30);
            myAnim.setInterpolator(interpolator);
            myAnim.setDuration(350);
            itemView.startAnimation(myAnim);

            if(mListener!=null) {
                Bitmap bitmap = null;
                Drawable d = art.getDrawable();
                if(d instanceof BitmapDrawable) bitmap = ((BitmapDrawable)d).getBitmap();
                else if(d instanceof RoundedDrawable) bitmap = ((RoundedDrawable)d).getSourceBitmap();
                mListener.onClickPlaylist(mPlaylistData.get(getAdapterPosition()), bitmap);
            }

        }

        @Override
        public boolean onTouch(View view, MotionEvent motionEvent) {
            if(currentColor!=Tool.getBaseColor()) {
                currentColor = Tool.getBaseColor();
                ((RippleDrawable) view_over.getBackground()).setColor(ColorStateList.valueOf(Tool.getBaseColor()));
            }
            return false;
        }
    }


    private static class PlaylistBitmapLoader extends AsyncTask<Void,Void,Bitmap> {
        private FeaturePlaylistAdapter mAdapter;
        private ItemHolder mItemHolder;
        private Playlist mPlaylist;

        PlaylistBitmapLoader(FeaturePlaylistAdapter adapter, Playlist playlist, ItemHolder item) {
            mAdapter = adapter;
            mItemHolder = item;
            mPlaylist = playlist;
        }
        @Override
        protected void onPostExecute(Bitmap bitmap) {
            mItemHolder.art.setImageBitmap(bitmap);
        }

        @Override
        protected Bitmap doInBackground(Void... v) {

            List<Song> l = mAdapter.getPlaylistWithListId(mItemHolder.getAdapterPosition(),mPlaylist.id);
            return AutoGeneratedPlaylistBitmap.getBitmap(mAdapter.mContext,l,false,false);
        }
    }

}